site_name: Traiectoria Optima
docs_dir: docs
site_dir: site

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - src
            - src/data
            - src/models/flight
            - src/exercises
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true

nav:
  - Home: index.md
  - Setup: setup.md
  - Documentation Standard: documentation-standard.md
  - API Reference: reference.md
  - Makefile: makefile.md
  - Glossary: glossary.md
  - Project:
      - Plan: project_plan.md
      - Report: report.md
      - Discussion: discussion.md
      - Data: data.md
      - Distance Formulas: distance_formulas.md
      - Software: software.md
      - Airlines: airlines.md
      - Passenger Name Records: passenger_name_records.md
      - Graph Algorithms Notes: graph-algorithms-notes.md
