from pathlib import Path

import hashlib
import json

import matplotlib
import pytest

# Use a non-interactive backend so plotting code under test never tries to
# open a GUI window during the test run.
matplotlib.use("Agg")

# The snapshot the loader tests run against. Tests assert exact counts, so
# they need data that cannot move underneath them -- `data/processed/` is
# regenerated by `make flight_network` and now holds the whole world.
#
# This is the pre-global dataset: United, US large airports, both endpoints.
# The id embeds a hash of the contents, so changing the data changes the id
# and this constant has to be updated deliberately rather than silently.
LEGACY_SNAPSHOT_ID = "2026-09-11-1528c4"


@pytest.fixture(scope="session")
def repo_root() -> Path:
    """Return the repository root.

    The `flight_planner` package takes CSV paths from its caller and knows
    nothing about the repository layout, so locating data is the test suite's
    job rather than the package's.

    Returns:
        Absolute `Path` to the repository root.
    """
    return Path(__file__).resolve().parents[1]


@pytest.fixture(scope="session")
def processed_data_dir(repo_root: Path) -> Path:
    """Return the pipeline's current output directory.

    Contents change whenever `make flight_network` runs, so prefer a snapshot
    for anything asserting specific values.

    Returns:
        Absolute `Path` to `data/processed`.
    """
    return repo_root / "data" / "processed"


@pytest.fixture(scope="session")
def legacy_snapshot_dir(repo_root: Path) -> Path:
    """Return the immutable snapshot the loader tests assert against.

    Returns:
        Absolute `Path` to the snapshot directory.
    """
    return repo_root / "data" / "snapshots" / LEGACY_SNAPSHOT_ID


@pytest.fixture(scope="session")
def airports_csv(legacy_snapshot_dir: Path) -> Path:
    """Return the snapshot's `airports.csv`.

    Returns:
        Absolute `Path` to the airports CSV.
    """
    return legacy_snapshot_dir / "airports.csv"


@pytest.fixture(scope="session")
def routes_csv(legacy_snapshot_dir: Path) -> Path:
    """Return the snapshot's `routes.csv`.

    Returns:
        Absolute `Path` to the routes CSV.
    """
    return legacy_snapshot_dir / "routes.csv"


# --- Hand-built snapshots -------------------------------------------------
# Written by hand rather than generated, so the tests pin the on-disk contract
# a snapshot has to satisfy instead of agreeing with whatever the pipeline
# currently emits.

AIRPORTS_CSV = (
    "name,iso_country,iso_region,continent,municipality,iata_code,icao_code,"
    "latitude_deg,longitude_deg,elevation_ft,scheduled_service,type,wikipedia_link\n"
    '"San Francisco International Airport",US,US-CA,NA,"San Francisco",SFO,KSFO,'
    "37.619806,-122.374821,13,yes,large_airport,\n"
    '"Logan International Airport",US,US-MA,NA,Boston,BOS,KBOS,'
    "42.364347,-71.005181,20,yes,large_airport,\n"
)

ROUTES_CSV = (
    "flight_number,airline_code,source_airport_code,destination_airport_code,"
    "codeshare,stops,equipment,distance_km\n"
    "UA1876,UA,SFO,BOS,,0,320,4341.0\n"
)


@pytest.fixture
def sample_csv():
    """Return the CSV text the hand-built snapshots are made of."""
    return {"airports.csv": AIRPORTS_CSV, "routes.csv": ROUTES_CSV}


@pytest.fixture
def make_snapshot():
    """Return a factory writing a complete, self-consistent snapshot."""

    def write(directory, airports=AIRPORTS_CSV, routes=ROUTES_CSV, **manifest):
        directory.mkdir(parents=True, exist_ok=True)
        contents = {"airports.csv": airports, "routes.csv": routes}
        for filename, text in contents.items():
            (directory / filename).write_text(text)

        payload = {
            "snapshot_id": directory.name,
            "created": "2026-09-11T00:00:00+00:00",
            "source_commit": "abc123",
            "generator": "test",
            "criteria": {"airline": "UA"},
            "files": {
                filename: {
                    "sha256": hashlib.sha256(text.encode()).hexdigest(),
                    "bytes": len(text.encode()),
                    "rows": text.count("\n") - 1,
                }
                for filename, text in contents.items()
            },
        }
        payload.update(manifest)
        (directory / "manifest.json").write_text(json.dumps(payload))
        return directory

    return write


@pytest.fixture
def snapshot_dir(tmp_path, make_snapshot):
    """Return a freshly written snapshot directory."""
    return make_snapshot(tmp_path / "2026-09-11-abc123")
